#!/usr/bin/env python3
"""Regenerate characters/sw.js.

The service worker serves the sheets from a versioned cache. The version is a
hash of every file it precaches, so editing a sheet changes the version, which
changes sw.js, which is what makes browsers notice there is an update at all.

    python tools/build_sw.py

Run it after ANY change under characters/ and commit the regenerated sw.js.
If you forget, players still self-heal on their next online visit (HTML, CSS and
JS are served stale-while-revalidate), but they see the old page once first.
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)            # the characters/ directory

# Everything the app needs with no network. Order is irrelevant; the list is
# sorted before hashing so the version is stable across platforms.
INCLUDE_SUFFIX = (".html", ".css", ".js", ".jpg", ".png", ".woff2", ".webmanifest")
SKIP_NAMES = {"sw.js"}                  # never let the worker cache itself
SKIP_DIRS = {"tools", ".git"}

def collect():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            if fn in SKIP_NAMES or not fn.endswith(INCLUDE_SUFFIX):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
            out.append((rel, full))
    return sorted(out)


def main():
    files = collect()
    if not files:
        sys.exit("no assets found under %s" % ROOT)

    h = hashlib.sha256()
    for rel, full in files:
        h.update(rel.encode("utf-8"))
        with open(full, "rb") as fh:
            h.update(hashlib.sha256(fh.read()).digest())
    version = h.hexdigest()[:12]

    # "./" is what a bare /characters/ navigation resolves to; cache it as well
    # as index.html so the start_url works offline.
    urls = ["./"] + [rel for rel, _ in files]
    precache = ",\n  ".join('"%s"' % u for u in urls)

    sw = TEMPLATE.replace("__VERSION__", version).replace("__PRECACHE__", precache)
    dest = os.path.join(ROOT, "sw.js")
    with open(dest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(sw)

    print("wrote %s" % dest)
    print("  version   %s" % version)
    print("  precached %d files (%.0f KB)"
          % (len(files), sum(os.path.getsize(f) for _, f in files) / 1024))


TEMPLATE = r'''/* GENERATED by tools/build_sw.py - do not edit by hand.
   Re-run that script after changing anything under characters/. */
const VERSION = "__VERSION__";
const PRECACHE_CACHE = "mf-sheets-" + VERSION;

/* Scope is this file's directory, so the tracker at the site root is never
   intercepted and keeps behaving like a normal online page. */
const SCOPE = new URL("./", self.location).pathname;

const PRECACHE = [
  __PRECACHE__
];

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(PRECACHE_CACHE);
    /* cache.addAll rejects the whole batch if a single URL 404s, which would
       leave the app with no offline copy at all. Add individually so one
       missing portrait cannot break the install. */
    await Promise.all(PRECACHE.map((url) =>
      cache.add(new Request(url, { cache: "reload" }))
        .catch((err) => console.warn("[sw] could not precache", url, err))
    ));
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((k) => k.startsWith("mf-") && k !== PRECACHE_CACHE)
      .map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

/* Immutable-ish bytes: portraits, icons, fonts. Cheapest correct strategy. */
async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && (response.ok || response.type === "opaque")) {
    const cache = await caches.open(cacheName);
    cache.put(request, response.clone());
  }
  return response;
}

/* Things that change when the sheets are edited. Serve the cached copy at once
   so the app opens instantly and works with no signal, then quietly refresh it
   so a deploy that forgot to bump the version still lands on the next visit. */
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const network = fetch(request).then((response) => {
    if (response && response.ok) cache.put(request, response.clone());
    return response;
  }).catch(() => null);
  return cached || (await network) || fetch(request);
}

async function handleNavigation(request) {
  const url = new URL(request.url);
  /* A directory URL has no cache entry of its own; fall back to its index. */
  const key = url.pathname.endsWith("/") ? new Request(url.href + "index.html") : request;
  const cache = await caches.open(PRECACHE_CACHE);
  const cached = (await cache.match(key)) || (await cache.match(request));
  const network = fetch(request).then((response) => {
    if (response && response.ok) cache.put(key, response.clone());
    return response;
  }).catch(() => null);
  const response = cached || (await network);
  if (response) return response;
  /* Offline and never visited: the roster is the most useful thing to show. */
  return (await cache.match(SCOPE + "index.html")) ||
         new Response("<h1>Offline</h1><p>This sheet has not been saved for offline use yet.</p>",
                      { headers: { "Content-Type": "text/html; charset=utf-8" }, status: 503 });
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  /* Anything off-origin, and anything outside characters/, is left alone.
     Fonts ship with the repo now, so there is no cross-origin request to catch. */
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(SCOPE)) return;

  if (request.mode === "navigate") {
    event.respondWith(handleNavigation(request));
    return;
  }
  if (/\.(?:html|css|js|webmanifest)$/.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(request, PRECACHE_CACHE));
    return;
  }
  event.respondWith(cacheFirst(request, PRECACHE_CACHE));
});
'''

if __name__ == "__main__":
    main()
