/* GENERATED by tools/build_sw.py - do not edit by hand.
   Re-run that script after changing anything under characters/. */
const VERSION = "974a19665110";
const PRECACHE_CACHE = "mf-sheets-" + VERSION;

/* Scope is this file's directory, so the tracker at the site root is never
   intercepted and keeps behaving like a normal online page. */
const SCOPE = new URL("./", self.location).pathname;

const PRECACHE = [
  "./",
  "anta.html",
  "cronus_aldor.html",
  "fonts.css",
  "fonts/cinzel-var-latin.woff2",
  "fonts/inter-var-latin.woff2",
  "hanabi.html",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "jebrael_crux.html",
  "manifest.webmanifest",
  "mimic.html",
  "nadarr.html",
  "portraits/anta.jpg",
  "portraits/cronus_aldor.jpg",
  "portraits/hanabi.jpg",
  "portraits/jebrael_crux.jpg",
  "portraits/mimic.jpg",
  "portraits/nadarr.jpg",
  "portraits/sapphira.jpg",
  "portraits/sky_scarlet.jpg",
  "portraits/victoria.jpg",
  "portraits/whiskers.jpg",
  "portraits/wolffe_loudstrife.jpg",
  "pwa.js",
  "sapphira.html",
  "sheet.css",
  "sheet.js",
  "sky_scarlet.html",
  "victoria.html",
  "whiskers.html",
  "wolffe_loudstrife.html"
];

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(PRECACHE_CACHE);
    /* cache.addAll rejects the whole batch if a single URL 404s, which would
       leave the app with no offline copy at all. Add individually so one
       missing portrait cannot break the install. */
    await Promise.all(PRECACHE.map((url) =>
      cache.add(new Request(url, { cache: "reload" }))
        .catch((err) => console.warn("[sw] could not precache", url, err))
    ));
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((k) => k.startsWith("mf-") && k !== PRECACHE_CACHE)
      .map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

/* Immutable-ish bytes: portraits, icons, fonts. Cheapest correct strategy. */
async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && (response.ok || response.type === "opaque")) {
    const cache = await caches.open(cacheName);
    cache.put(request, response.clone());
  }
  return response;
}

/* Things that change when the sheets are edited. Serve the cached copy at once
   so the app opens instantly and works with no signal, then quietly refresh it
   so a deploy that forgot to bump the version still lands on the next visit. */
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const network = fetch(request).then((response) => {
    if (response && response.ok) cache.put(request, response.clone());
    return response;
  }).catch(() => null);
  return cached || (await network) || fetch(request);
}

async function handleNavigation(request) {
  const url = new URL(request.url);
  /* A directory URL has no cache entry of its own; fall back to its index. */
  const key = url.pathname.endsWith("/") ? new Request(url.href + "index.html") : request;
  const cache = await caches.open(PRECACHE_CACHE);
  const cached = (await cache.match(key)) || (await cache.match(request));
  const network = fetch(request).then((response) => {
    if (response && response.ok) cache.put(key, response.clone());
    return response;
  }).catch(() => null);
  const response = cached || (await network);
  if (response) return response;
  /* Offline and never visited: the roster is the most useful thing to show. */
  return (await cache.match(SCOPE + "index.html")) ||
         new Response("<h1>Offline</h1><p>This sheet has not been saved for offline use yet.</p>",
                      { headers: { "Content-Type": "text/html; charset=utf-8" }, status: 503 });
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  /* Anything off-origin, and anything outside characters/, is left alone.
     Fonts ship with the repo now, so there is no cross-origin request to catch. */
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(SCOPE)) return;

  if (request.mode === "navigate") {
    event.respondWith(handleNavigation(request));
    return;
  }
  if (/\.(?:html|css|js|webmanifest)$/.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(request, PRECACHE_CACHE));
    return;
  }
  event.respondWith(cacheFirst(request, PRECACHE_CACHE));
});
